name: CI - Publish in Chrome Store
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout by SHA
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha }}

      - name: Install dependencies
        run: npm ci

      - name: Create build
        run: npm run build

      - name: Make Zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./dist/app.zip ./dist


      - name: Publish
        uses: Passiverecords/chrome-extension-upload-action@1.4.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          file-name: './dist/app.zip'
          app-id: 'legogknlfnllbmijpohabichmkmhcefh'
          publish: true
